### ISSUE TITLE
Add specificity to utility directive styles

### ISSUE THREAD

**Issue by pauleustice** [Legal-and-General/canopy#49]
When using LgPadding and LgMargin, I've found that the styles applied by the directives can be overridden as they have low specificity. Perhaps they could make use of `!important` to overcome this?

**Comment by owensgit** [comment]
@pauleustice thanks for raising this. My instinctual reaction with `!important` is that it should be avoided. But perhaps this is case where it's actually appropriate 🤔 

Looking at the CSS, I can see the utility classes are specified inside the `body`:

```css
body {
  // utility classes require additional specificity
  ...
  @each $val in $spacing-list {
    .lg-margin__top--#{$val} {
      margin-top: space($val);
    }
  ...
  }
}
```

Alternatively, maybe they could be a level higher, and placed inside the `html` to give them even higher specificity.

Could you provide an example/scenario where they are being overridden, it'll be good to figure our why the `body` CSS above is not specific enough.
_(please note that we can't share specific details about our digital products in this repo as it's open source._ 

It'll also be good to get the views of the rest of the team CC @elenagarrone  @thatguynamedandy  @aaronBery.
